### ISSUE TITLE
Spatial transformer network understanding

### ISSUE THREAD

**Issue by riccardosamperna** [uncbiag/mermaid#131]
Hello @marcniethammer,
Thank you for making the code available, really interesting work.

I was looking into some of the code, in particular for the STN in 3D. I noticed that you are moving the channels around, here:https://github.com/uncbiag/mermaid/blob/dd068958000d41848d6eb882591fd5d765f36bbf/mermaid/libraries/functions/stn_nd.py#L83
why so?

I have also another question that is not about your code in particular but it is in general about the Pytorch grid_sample function. As you can see from [my question](https://github.com/pytorch/pytorch/issues/24870#issuecomment-533526631) , I am still not sure about how to correctly use grid_sample in case of registration. Have you solved this problem yourself?

**Comment by hbgtjxzbbx** [comment]
Hi @riccardosamperna   thanks for your interests. 
The grid_sample organize the coord like this [way](https://discuss.pytorch.org/t/how-does-grid-sample-x-grid-work/15401/4)

In this 2d case, you can find the code like this
real ix = THTensor_fastGet4d(grid, n, h, w, 0);
real iy = THTensor_fastGet4d(grid, n, h, w, 1);


You can find the input grid is in shape (N, Depth, Height, Width, 3), while the last channel should be ordered like (x width, y height, z depth) 
In our code,  we assume the channel in grid follows the same order as  ( Depth, Height, Width) , which means (z depth, y height, x width) so we transpose the coord.

About the grid_sample,  your option1 seems make sense to me. Don't worry about the value outside of -1, and 1, that's what boundary condition takes care.

**Comment by riccardosamperna** [comment]
Thank you for your explanation.
