### ISSUE TITLE
Does it support Cross-modal image registration?

### ISSUE THREAD

**Issue by uchihatashi** [uncbiag/mermaid#138]
I am looking for Cross model image registration for some of my projects and I am wondering will it support cross-modal images.

**Comment by hbgtjxzbbx** [comment]
Hi Tashi
Thanks for your interests. A short answer is yes. 
For image registration task, the "similarity measure" and the "registration mode"l together determine the behavior of the model.
The similarity term measure the difference between the warped and the target. 
You task is about cross-modal registration, where the focus is on the "similarity measure", and an ideal solution is some "cross-modality" loss, e.g., NCC, mutual information, e.t.c.
The mermaid supports NCC and more advance localized NCC. https://github.com/uncbiag/mermaid/blob/d0f4a7c044c0e6e81de2fb5a3fd708bf7c872fce/mermaid/similarity_measure_factory.py#L262

But just to clarify that the mermaid is a toolkit focusing on the "registration model", or more specific,  the fluid based registration model.
