### ISSUE TITLE
force registration running on CPU

### ISSUE THREAD

**Issue by colddie** [uncbiag/mermaid#147]
Hi,

How can I force the register_image on CPU? By default, example_simple_interface.py seems always run on GPU, even if CUDA_ON was set to false.

Thank you

**Comment by hbgtjxzbbx** [comment]
Hi colddie
thanks for the feedback. sorry for the confusion,  you can set CUDA_ON to False, and comment[ line 41 ](https://github.com/uncbiag/mermaid/blob/17d2015666cd228df25269778ce227bf9837150a/mermaid_demos/example_simple_interface.py#L41)
Then code should run on CPU.
