### ISSUE TITLE
Must I0 and I1 be resampled to the same spacing before registration?

### ISSUE THREAD

**Issue by Confusedisprecious** [uncbiag/mermaid#149]
Must the moving image and the reference image have the same spaing?

si.register_images(I0, I1, spacing, model_name='lddmm_shooting_map',
                   nr_of_iterations=100,
                   use_multi_scale=False,
                   visualize_step=5,
                   optimizer_name='sgd',
                   learning_rate=0.1,
                   rel_ftol=1e-7,
                   json_config_out_filename=('test2d_tst.json',
                                             'test2d_tst_with_comments.json'),
                   params='test2d_tst.json',
                   recording_step=None)
I0 and I1 must have the same spacing?Must I0 and I0 be resampled to the same spacing before registration?

**Comment by marcniethammer** [comment]
Yes, in the current implementation this is required. The images also need to be the same size. This could be changed (and likely should be changed) in a future version.
